### ISSUE TITLE
Python3 Command Not Found

### ISSUE THREAD

**Issue by EggEngineer** [f3rn0s/bitinfo#4]
Whenever I try to run bitinfo, the command python3 comes up as nonexistent, is there something I'm doing wrong?

**Comment by f3rn0s** [comment]
It uses python, (it's listed as a prerequisite) so you either haven't installed it or python3 is not on your PATH variable.

It depends on your OS but something like [google's python enviroment setup tutorial](https://cloud.google.com/python/setup) should help.

**Comment by EggEngineer** [comment]
I installed python 3.6 and 3.7 on my computer, so how would I put it on my path variable?

**Comment by f3rn0s** [comment]
Are you on windows or?

**Comment by EggEngineer** [comment]
Windows, yessir.

**Comment by f3rn0s** [comment]
https://superuser.com/questions/143119/how-do-i-add-python-to-the-windows-path#143121

**Comment by EggEngineer** [comment]
Thanks.

**Comment by EggEngineer** [comment]
Still didn't work, as Git Bash still says python3 is invalid.

**Comment by f3rn0s** [comment]
Try doing `echo $PATH` and see what's there.

You should be able to change path with something like `export PATH=$PATH:C:/somewindowsfolder/python37/`

**Comment by EggEngineer** [comment]
Python36 is a folder in the path, so why does it still not work? Or do I need Python37?

**Comment by f3rn0s** [comment]
Is that where your python is installed to? You should be making sure that it matches where your python installation is.

No, any version of python3 should work fine.

**Comment by EggEngineer** [comment]
Yup, it says and I quote. "Extractor/bin:/c/Users/Alex/AppData/Local/Microsoft/WindowsApps:/c/Python36:/c/Python36/scripts:/usr/bin/vendor_perl:/usr/bin/core_perl"

**Comment by f3rn0s** [comment]
You should be able to run `/c/Python36/python3` or `/c/Python36/python` as a command. Maybe on windows if you don't have python2 and python3 it just names python3 python?

**Comment by EggEngineer** [comment]
Neither of those commands or naming it python worked, I have an idea however. If I move it to System32 or the base C:\Windows directory, would that work?

**Comment by f3rn0s** [comment]
No. If the commands aren't working then your python is installed somewhere else

Go the start menu, search for python, right click properties then click "show file location" etc. to find where it is actually installed.

**Comment by f3rn0s** [comment]
Similarly, if you re-do the installation there is a tick box option to "Add python to your PATH" which is quite handy.

**Comment by EggEngineer** [comment]
I might need to do a reinstall, then. It seems like it's the way to go here.
